SELECT [patient_id]
      ,[first_name]
      ,[surname]
      ,[national_id]
      ,[date_of_birth]
      ,[disease]
      ,[severity]
      ,[admission_status]
      ,[ward]
      ,[admission_date]
      ,[discharge_date]
  FROM [stg_hospital_admissions].[dbo].[hospital_admissions_raw]
